"""add cve_analysis_data

Revision ID: fa55055d3c21
Revises: 4fdec65e9691
Create Date: 2025-11-15 21:18:47.616145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa55055d3c21'
down_revision: Union[str, Sequence[str], None] = '4fdec65e9691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('cve_analysis_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'cve_analysis_data')
    # ### end Alembic commands ###
